# Generated by Django 4.2.5 on 2023-09-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='viewinghistory',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
